default_install_hook_types:
# Mandatory to install both pre-commit and pre-push hooks (see https://pre-commit.com/#top_level-default_install_hook_types)
# Add new hook types here to ensure automatic installation when running `pre-commit install`
- pre-commit
- pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: format-check
    name: FRONTEND - Formatting (prettier)
    entry: sh -c "cd frontend && pnpm run format-check"
    pass_filenames: false
    language: system
    types_or: [ts, tsx]
    stages: [pre-commit]
  - id: lint-check
    name: FRONTEND - Linting (ESLint)
    entry: sh -c "cd frontend && pnpm run lint-check"
    language: system
    types_or: [ts, tsx]
    stages: [pre-commit]
    pass_filenames: false
  - id: type-check
    name: FRONTEND - Type checking (TypeScript)
    entry: sh -c "cd frontend && pnpm run type-check"
    language: system
    types_or: [ts, tsx]
    stages: [pre-commit]
